# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 83d435566f2cd443053e3ac65160792b8e24876fe37035af5cac7c5c6d8cca1dc82d8bacf2598359b0fdf8455f4c59db76ee7cf2fada254893407b49ce637677

test:
  secret_key_base: 2bf0f04218d0ee55d36cccc9984f054759b4547f2fb59c6bb2d26091d04e879251070860bb1f1e21fad384ae7ffb798d10a8126d803e8943149cd581c6fd48f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
